### ISSUE TITLE
Automated tested updates broken

### ISSUE THREAD

**Issue by lukpueh** [in-toto/demo#24]
Looks like we don't [auto-test the demo on updates](https://github.com/in-toto/demo/pull/18/checks) as [we used to do before](https://github.com/in-toto/demo/pull/15/checks) anymore. The travis build badge in the [README](https://github.com/in-toto/demo#in-toto-demo-) also 404's. 

Todo:
- https://github.com/in-toto/demo/pull/19
- Troubleshoot Travis config or switch to GitHub Actions

**Comment by adityasaky** [comment]
Closed in #28
