### ISSUE TITLE
in-toto verify failing using ED25519

### ISSUE THREAD

**Issue by KyalSmith** [in-toto/demo#52]
I followed the steps in the in-toto/demo as described up to "Verify final product"
and I got the following error when running the command:
in-toto verify --layout root.layout --layout-keys alice.pub
inspection failed: step 'clone' requires '1' link metadata file(s), found '0'

The only way I have diverged from the in-toto/demo is that I generated the bob and carl private and public keys using the following commands:
openssl genpkey -algorithm ed25519 -out bob
openssl pkey -in bob -pubout -out bob.pub
openssl genpkey -algorithm ed25519 -out carl
openssl pkey -in bob -pubout -out carl.pub

I then used the following command to generate the json files required by the create_layout.py:
in-toto key layout bob.pub
in-toto key layout carl.pub

The output of which, I saved as bob_json.pub and carl_json.pub which I then modified the create_layout.py accordingly to reference these files.

I have included the results stored in the final_product directory as a tar.gz file.
[final_product.tar.gz](https://github.com/in-toto/demo/files/11536386/final_product.tar.gz)

**Comment by adityasaky** [comment]
Hi @kyalSmith, are you using in-toto-golang?

**Comment by KyalSmith** [comment]
That is correct.
Would you prefer me to create the issue there?
https://github.com/in-toto/in-toto-golang

**Comment by adityasaky** [comment]
And did you leave the rest of the script as is? You used in-toto-python to create the links, right?

**Comment by adityasaky** [comment]
Can you share the versions of the in-toto tools you used? Both the Python and Go implementations have had some recent-ish updates which could be causing these sorts of issues.

**Comment by KyalSmith** [comment]
I have included the create_layout.py file that I have modified in the final_product.tar.gz. 
The only lines I modified are line 12 and 13 regarding the file references and the method "import_ed25519_publickey_from_file".

By the in-toto-python file used to create the links, are you referring to:
"in-toto-record" and "in-toto-run"

Unfortunately Not, I used the golang equivalents:
"in-toto record" and "in-toto run"

The in-toto golang code I got from:
[https://github.com/in-toto/in-toto-golang](url)
The branch being "master"
Which I compiled using "make build" and simply copied the in-toto binary to my /usr/bin/.

My current python version is : 3.10.10
and golang is: 1.20.3

**Comment by KyalSmith** [comment]
Apologies I am using the "main" branch from:
[https://github.com/in-toto/demo](url)

**Comment by adityasaky** [comment]
Interesting. I think the issue is because of the `stdout` recorded in byproducts. There's a trailing newline which is causing an issue when deserializing from JSON. `jq` is complaining about this as is the in-toto python implementation when I try to verify that file's signature directly (`in-toto-sign --verify -f clone.0a88087a.link -k bob_json.pub -t ed25519`). The signature on the update-version link verifies fine but the one on `package` again runs into this issue, and it again has stdout recorded. The backtrace indicates a specific col in the metadata causing the issue which matches the `\n` character in the string representation of the link.

I'm speculating that the Go implementation is running into a similar issue with the JSON decoding, just that the specific error got suppressed before it could make it back to you. I'm also speculating that we haven't run into this before because this is a relatively recent DSSE specific change in the stack--this character was likely getting escaped when used with cjson. At this point, I'm going to cc @lukpueh in as well for his expertise with this.

Separately, @KyalSmith, could you try generating a set of metadata by removing `--use-dsse`?

**Comment by KyalSmith** [comment]
Apologies, its a bit late on this side. Will do as soon as I get a change tomorrow.

**Comment by KyalSmith** [comment]
I removed the --use-dse and when running the:
in-toto verify --layout root.layout --layout-keys alice.pub

I got the following error:
inspection failed: artifact verification failed for Inspection 'untar', materials [update-version.0a88087a.link clone.0a88087a.link package.733aeb2b.link] disallowed by rule [DISALLOW *]

I have included the contents of the final_product directory below:
[final_product2.tar.gz](https://github.com/in-toto/demo/files/11543865/final_product2.tar.gz)

**Comment by adityasaky** [comment]
Great, that's a known deviation between in-toto-python and in-toto-golang luckily.

When an inspection is executed, link metadata is generated that records all the artifacts in the PWD. The python implementation ignores some by default (https://github.com/in-toto/in-toto/blob/develop/in_toto/settings.py#L33) while the go implementation does not. So if you clean up that directory and verify using in-toto-python, it will pass. Alternatively, modifying the layout to allow the link metadata will also do the trick. We've got some plans to test and squash these deviations between implementations.

As for the DSSE specific issue, I suspect this goes across in-toto implementations so I'm not sure where to open the ticket. @lukpueh wdyt?

**Comment by adityasaky** [comment]
The layout can continue to be DSSE, the only issue seems to be when `\n` is included in the payload. By modify the layout, I meant you can add rules to the inspection to `ALLOW *.link` before `DISALLOW *` so that the link metadata for clone, update-version, package etc don't cause an issue.

**Comment by adityasaky** [comment]
No, no, the change belongs in https://github.com/in-toto/demo/blob/main/owner_alice/create_layout.py#L70 and https://github.com/in-toto/demo/blob/main/owner_alice/create_layout.py#L79 so that the additional rules are also part of the signed payload.

**Comment by KyalSmith** [comment]
I see, thank will try now and see.

**Comment by KyalSmith** [comment]
Okay so without using the --use-dse argument and modifying the create_layout.py as you specified now returns and exit status of 0.

Thank You.

**Comment by KyalSmith** [comment]
I'm assuming that DSSE stands for Dynamic Searchable Symmetric Encryption?
I'm wondering what functionality is missing when I do not use the flag.
The Help on in-toto states:
      --use-dsse                          Create metadata using DSSE instead of the legacy signature wrapper.
Could not using this pose a serious security vulnerability?

**Comment by adityasaky** [comment]
DSSE is a new signature envelope: https://github.com/secure-systems-lab/dsse

It addresses some concerns that are detailed here: https://github.com/secure-systems-lab/dsse/blob/master/background.md

While there's a bug here, it shouldn't block long term adoption / use of DSSE in in-toto.
