### ISSUE TITLE
securesystemlib 1.0.0 breaks demo

### ISSUE THREAD

**Issue by tonylturner** [in-toto/demo#69]
New installation pulls https://github.com/secure-systems-lab/securesystemslib/releases/tag/v1.0.0 which has removed `interface` and now breaks the demo. Manually specifying with `pip install securesystemslib==0.31.0` worked for me. 

https://github.com/secure-systems-lab/securesystemslib/blob/v1.0.0/CHANGELOG.md

**Comment by lukpueh** [comment]
Thanks for the report! I just updated the demo requirements.txt to use the latest in-toto version, which has a version constraint for securesystemslib. #70 

This should work now without manually downgrading securesystemslib.
